services:
  postgres:
    image: jubo-test/postgres:18.1
    build:
      context: ./src/infra/postgres-sql
      dockerfile: Dockerfile
    restart: always
    volumes:
      - postgres-18-data:/var/lib/postgresql
      - ./src/infra/postgres-sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${ROOT_PWD}
      POSTGRES_INITDB_USERNAME: jubo
      POSTGRES_INITDB_PASSWORD: ${JUBO_PWD}
      POSTGRES_INITDB_APP_USERNAME: jubo_app
      POSTGRES_INITDB_APP_PASSWORD: ${JUBO_APP_PWD}
      LANG: zh_TW.UTF-8
    networks:
      - default
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  postgres-18-data:

networks:
  default:
    name: jubo-test_default